{% macro do_baz() -%}
params:
  ENVIRONMENT: {{ "ENVIRONMENT" | env }}
  SECRETS_PASS: secrets_pass
  NUM_NODES: num_nodes
inputs:
- name: do_baz
- name: pipelines-repo
- name: secrets-repo
outputs:
- name: do_baz
platform: linux
image_resource:
  type: docker-image
  source:
    repository: lab/python-image
    username: {{ docker_user }}
    password: {{ "DOCKER_PASSWORD" | env }}
run:
  path: echo
  args: ["Hello, world!"]
{%- endmacro %}