#@ load("@ytt:data", "data")
#@ def do_foo():
params:
  ENVIRONMENT: (( grab $ENVIRONMENT ))
  SECRETS_PASS: secrets_pass
  NUM_NODES: num_nodes
inputs:
- name: pipelines-repo
- name: secrets-repo
outputs:
- name: do_foo
platform: linux
image_resource:
  type: docker-image
  source:
    repository: lab/python-image
    username: docker_user
    password: docker_password
run:
  path: echo
  args: ["Hello, world!"]
#@ end